# --- 게임 설정 ---
INITIAL_STARS = 3
INITIAL_CARDS_EACH_TYPE = 2
TOTAL_PLAYERS = 3 # 시뮬레이션 규모 조절 (원작: 30)
MAX_TURNS = 8 # 4시간 / 10분
TIME_PER_TURN = 10 # 분

# --- 플레이어 상태 ---
PLAYER_STATUS_ACTIVE = "ACTIVE"
PLAYER_STATUS_ELIMINATED_NO_STAR = "ELIMINATED (No Stars)"
PLAYER_STATUS_ELIMINATED_TIME_OUT = "ELIMINATED (Time Out)"
PLAYER_STATUS_OUT_SUCCESS = "OUT (Success)"
